In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

dataset = pd.read_csv("Placement.csv")

dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [5]:
dataset['ssc_p'].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64

In [ ]:
# freqData = pd.DataFrame(columns=['Unique_values', 'Frequency','Relative frequency','Cumm Relative frequency'])
# freqData

In [ ]:
# freqData['Unique_values'] = dataset['ssc_p'].value_counts().index
# freqData['Frequency'] = dataset['ssc_p'].value_counts().values
# freqData['Frequency'] = dataset['ssc_p'].value_counts().values
# freqData['Relative frequency'] = dataset['ssc_p'].value_counts().values / dataset['ssc_p'].value_counts().values.sum()
# freqData['Cumm Relative frequency'] = freqData['Relative frequency'].cumsum()

# freqData

In [7]:
def generateFrequencyDetails(column, dataset):
    freqData = pd.DataFrame(columns=['Unique_values', 'Frequency','Relative_frequency','Cumm_Relative_frequency'])
    
    freqData['Unique_values'] = dataset[column].value_counts().index
    freqData['Frequency'] = dataset[column].value_counts().values
    freqData['Relative_frequency'] = dataset[column].value_counts().values / dataset[column].value_counts().values.sum()
    freqData['Cumm_Relative_frequency'] = freqData['Relative_frequency'].cumsum()
    
    return freqData

In [12]:
generateFrequencyDetails('ssc_p', dataset)

     Unique_values  Frequency  Relative_frequency  Cumm_Relative_frequency
0            62.00         11            0.051163                 0.051163
1            63.00         10            0.046512                 0.097674
2            67.00          9            0.041860                 0.139535
3            52.00          9            0.041860                 0.181395
4            73.00          9            0.041860                 0.223256
..             ...        ...                 ...                      ...
98           69.70          1            0.004651                 0.981395
99           80.92          1            0.004651                 0.986047
100          83.00          1            0.004651                 0.990698
101          86.50          1            0.004651                 0.995349
102          80.60          1            0.004651                 1.000000

[103 rows x 4 columns]

In [16]:
#For Continous numerical data Frequency analysis is not useful, because unique values will be very less
#due to decimal and small differences
#Analysing data in Ranges will be very useful.

#Define the ranges, the data needs to be segregated
ssc_p_bins = [30,40,50,60,70,80,90,100] #30-40, 40-50, ....90-100

#categorize data into the defined ranges
categories_ssc_p = pd.cut(dataset['ssc_p'], ssc_p_bins)
categories_ssc_p

0      (60, 70]
1      (70, 80]
2      (60, 70]
3      (50, 60]
4      (80, 90]
         ...
210    (80, 90]
211    (50, 60]
212    (60, 70]
213    (70, 80]
214    (60, 70]
Name: ssc_p, Length: 215, dtype: category
Categories (7, interval[int64, right]): [(30, 40] < (40, 50] < (50, 60] < (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [17]:

# Add the categorized column of ssc_p in dataset
dataset['categories_ssc_p'] = categories_ssc_p

dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,categories_ssc_p
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,"(60, 70]"
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,"(70, 80]"
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,"(60, 70]"
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,"(50, 60]"
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,"(80, 90]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,"(80, 90]"
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,"(50, 60]"
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,"(60, 70]"
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,"(70, 80]"
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,"(60, 70]"

In [18]:
#Perform frequency analysis for the categorized column
generateFrequencyDetails('categories_ssc_p', dataset)

  Unique_values  Frequency  Relative_frequency  Cumm_Relative_frequency
0      (60, 70]         79            0.367442                 0.367442
1      (70, 80]         55            0.255814                 0.623256
2      (50, 60]         40            0.186047                 0.809302
3      (80, 90]         29            0.134884                 0.944186
4      (40, 50]         12            0.055814                 1.000000
5      (30, 40]          0            0.000000                 1.000000
6     (90, 100]          0            0.000000                 1.000000